image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add libffi-dev openssl-dev python python-dev py-pip build-base
  - pip install docker-compose

build:
  only:
    - master
  stage: build
  script:
    - "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build"

after_script:
  - "docker ps"


#build:
#  only:
#    - master
#  before_script:
#    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
#  script:
#    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
#    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
#  after_script:
#    - docker logout ${CI_REGISTRY}
#  stage: build
#  tags:
#    - docker
#