image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add libffi-dev openssl-dev python python-dev py-pip build-base
  - pip install docker-compose

build:
  only:
    - master
  stage: build
  before_script:
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build"
    - docker push ${CI_REGISTRY_IMAGE}
  after_script:
    - docker logout ${CI_REGISTRY}
    - "docker ps"
  tags:
    - docker