image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
    stage: build
    script:
        - "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build"

after_script:
  - "docker ps"