version: '3.7'

services:
  webapp:
    image: ci-cd-webapp
    container_name: ci-cd-webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5005 #;https://+:5006
    restart: always
    ports:
      - "5005:5005"